Repository OneGround/ZGW-APIs, pull requests merged in 2025-09, with the labels that each got.

#87 Add support for self issued jwt tokens
  AUTHENTICATION.md
  getting-started/docker-compose/README.md
  getting-started/docker-compose/docker-compose.yml
  localdev/README.md
  localdev/docker-compose.yml
  src/Directory.Packages.props
  src/OneGround.ZGW.Autorisaties.WebApi/Program.cs
  src/OneGround.ZGW.Besluiten.WebApi/Program.cs
  src/OneGround.ZGW.Catalogi.WebApi/Program.cs
  src/OneGround.ZGW.Common.Web/Authentication/AuthenticationSchemeSelector.cs
  src/OneGround.ZGW.Common.Web/Authentication/ZGWAuthentication.cs
  src/OneGround.ZGW.Common.Web/Authentication/ZgwAuthenticationConstants.cs
  src/OneGround.ZGW.Common.Web/ZGW.Common.Web.csproj
  src/OneGround.ZGW.Documenten.Messaging.Listener/Program.cs
  src/OneGround.ZGW.Documenten.WebApi/Program.cs
  src/OneGround.ZGW.Notificaties.WebApi/Program.cs
  src/OneGround.ZGW.Zaken.WebApi/Program.cs
  src/appsettings.Shared.json
Labels: Documentation

#91 FUND-2001 ZRC 1.5 Create- and update zaakobject handlers should validate zaakobjecttype (ZTC 1.3)
  src/OneGround.ZGW.Zaken.Web/Handlers/v1/5/CreateZaakObjectCommandHandler.cs
  src/OneGround.ZGW.Zaken.Web/Handlers/v1/5/UpdateZaakObjectCommandHandler.cs
Labels: Bug, Zaken API

#94 FUND-1762 Log ApiVersion header
  src/OneGround.ZGW.Common.Web/Middleware/EnrichedLoggingMiddleware.cs
Labels: Autorisaties API, Referentielijsten API, Besluiten API, Documenten API, Notificaties API, Zaken API, Catalogi API, Improvement

#95 FUND-2081 - Improvements regarding Polaris scan
  src/OneGround.ZGW.Common/Helpers/TempFileHelper.cs
  src/OneGround.ZGW.Documenten.Services.Ceph/CephDocumentServices.cs
  src/Tests/OneGround.ZGW.Catalogi.WebApi.UnitTests/BusinessRulesTests/ConceptBusinessRulesTest.cs
  src/Tests/OneGround.ZGW.Common.UnitTests/TempFileHelperTests.cs
  src/Tests/OneGround.ZGW.Documenten.WebApi.UnitTests/BusinessRulesTests/v1/EnkelvoudigInformatieObjectBusinessRuleTests.cs
Labels: Improvement, Maintenance

#98 FUND-1494 Added AddCatalogusAsync for CatalogiServiceAgent
  src/OneGround.ZGW.Catalogi.ServiceAgent/v1/3/CatalogiServiceAgent.cs
  src/OneGround.ZGW.Catalogi.ServiceAgent/v1/3/ICatalogiServiceAgent.cs
Labels: Catalogi API
